address_bar_and_search:
- test_search_mode_exits_correctly
- test_use_different_search_shortcut_while_already_in_search_mode
- test_paste_and_go_opens_correct_url
- test_verify_url_after_tab_switch_with_search_mode
- test_ctrl_enter_completes_link_and_can_refresh
- test_disable_websearch_from_awesome_bar
- test_searchmode_cleared_on_engine_removal
- test_switch_to_existing_tab_when_having_the_same_URL
- test_delete_history_entry_via_firefox_suggest_completion_list
- test_addressbar_bookmarks_when_history_disabled
tabs:
- test_change_position_of_pinned_tabs
- test_close_pinned_tab_via_mouse
- test_close_tab_through_middle_mouse_click
- test_display_customize_button
- test_open_new_bg_tab_via_mouse_and_keyboard
- test_pin_unpin_selected_tabs
- test_play_mute_unmute_tabs_via_toggle
- test_reload_overiding_cache_keys
- test_reload_tab_via_keyboard
