address_bar_and_search:
- test_adaptive_history_autofill
- test_add_engine_address_bar
- test_added_open_search_engine_default
- test_addon_suggestion
- test_addressbar_search_engine_keywords
- test_copied_url_contains_https
- test_ctrl_enter_fixes_url
- test_default_search_provider_change_awesome_bar
- test_default_search_provider_change_legacy_search_bar
- test_dont_show_search_suggestions_in_private_window
- test_google_search_counts_us
- test_google_withads_url_bar_us
- test_insertion_point_no_search_terms_display
- test_no_suggestions_for_empty_query
- test_non_sponsored_topsite_context_menu_option
- test_refresh_firefox_dialog
- test_sap_google_adclick
- test_seach_suggestions_can_be_disabled
- test_search_code_google_non_us
- test_search_code_google_us
- test_search_engine_selector
- test_search_mode_appears_after_input
- test_search_mode_persists_mixed_with_bing
- test_search_modes_for_sites
- test_search_string_displayed_when_addressbar_unfocused
- test_search_suggestions
- test_search_term_persists
- test_searchbar_display_alpenglow_theme
- test_searchbar_on_engines_remove_restore
- test_searchbar_results_shown_in_a_new_tab
- test_searchmode_change_tab
- test_server_not_found_error
- test_server_not_found_error_pb
- test_suggestion_engine_selection
- test_switch_to_existing_tab_when_having_the_same_URL
- test_tile_menu_options
audio_video:
- test_allow_audio_video_functionality
- test_block_audio_video_functionality
- test_users_actions_saved_on_reload
bookmarks_and_history:
- test_add_new_other_bookmark
- test_bookmark_via_bookmark_menu
- test_bookmark_website_via_star_button
- test_clear_all_history
- test_clear_recent_history_displayed
- test_delete_bookmarks_from_toolbar
- test_delete_other_bookmarks
- test_deleted_page_not_remembered
- test_edit_bookmark_from_bookmark_menu
- test_edit_bookmark_via_star_button
- test_history_menu_from_different_places
- test_import_bookmarks_chrome
- test_import_bookmarks_edge
- test_open_all_bookmarks_from_bookmarks_toolbar
- test_open_bookmark_in_new_window_via_toolbar_context_menu
- test_open_bookmark_in_private_window_via_toolbar_context_menu
- test_open_bookmarks_from_toolbar
- test_open_websites_from_history
- test_opened_website_in_new_tab_present_in_hamburger_history_menu
- test_opened_website_in_new_window_present_in_hamburger_history_menu
- test_opened_website_present_in_hamburger_history_menu
- test_private_window_website_not_in_history
- test_toggle_bookmarks_toolbar
- test_user_can_forget_history
downloads:
- test_add_mime_type_doc
- test_add_zip_type
- test_download_pdf
- test_download_pdf_from_context_menu
- test_mixed_content_download_via_https
- test_set_always_ask_file_type
drag_and_drop:
- test_copy_entire_row_column
- test_copy_from_an_editor_paste_in_another
- test_copy_hyperlink_table
- test_copy_table_header
- test_paste_image_text
find_toolbar:
- test_find_in_pdf
- test_find_toolbar_nav
- test_find_toolbar_search
form_autofill:
- test_address_autofill_attribute
- test_autofill_cc_cvv
- test_autofill_credit_card
- test_autofill_credit_card_doorhanger
- test_autofill_credit_card_enable
- test_autofill_credit_card_four_fields
- test_cc_clear_form
- test_clear_form
- test_create_new_cc_profile
- test_create_profile_autofill
- test_delete_cc_profile
- test_edit_credit_card
- test_enable_disable_autofill
- test_form_autofill_suggestions
- test_name_autofill_attribute
- test_private_mode_info_not_saved
- test_telephone_autofill_attribute
- test_updating_address
- test_updating_credit_card
geolocation:
- test_geolocation_shared_via_html5
- test_geolocation_shared_via_w3c_api
language_packs:
- test_language_pack_install_addons
- test_language_pack_install_preferences
menus:
- test_copy_paste_actions
- test_frequently_used_context_menu
- test_hyperlink_context_menu
- test_image_context_menu_actions
- test_tab_context_menu_actions
- test_tab_context_menu_close
networking:
- test_default_dns_protection
- test_http_site
notifications:
- test_audio_video_permissions_notification
- test_camera_permissions_notification
- test_deny_geolocation
- test_deny_screen_capture
- test_geolocation_prompt_presence
- test_microphone_permissions_notification
- test_notifications_displayed
- test_screen_share_permission_prompt
- test_webextension_completed_installation_successfully_displayed
password_manager:
- test_about_logins_navigation_from_context_menu
- test_about_logins_navigation_from_hamburger_menu
- test_about_logins_search_username
- test_about_logins_search_website
- test_add_password_non_ascii_chars
- test_add_password_save_valid_data
- test_add_primary_password
- test_auto_saved_generated_password_context_menu
- test_autocomplete_dropdown_is_toggled_for_focused_login_fields_on_page_load
- test_can_view_password_when_PP_enabled
- test_changes_made_in_edit_mode_are_saved
- test_delete_login
- test_multiple_saved_logins
- test_never_save_login_via_doorhanger
- test_password_csv_correctness
- test_password_csv_export
- test_primary_password_triggered_on_about_logins_access
- test_save_login_via_doorhanger
- test_saved_hyperlink_redirects_to_corresponding_page
- test_update_login_via_doorhanger
pdf_viewer:
- test_add_image_pdf
- test_download_pdf_with_form_fields
- test_download_triggered_on_content_disposition_attachment
- test_open_pdf_in_FF
- test_pdf_data_can_be_cleared
- test_pdf_download
- test_pdf_input_numbers
- test_pdf_navigation
- test_zoom_pdf_viewer
preferences:
- test_check_for_updates
- test_clear_cookie_data
- test_firefox_home_new_tabs
- test_firefox_home_on_launch
- test_lang_pack_changed_from_about_prefs
- test_manage_cookie_data
- test_never_remember_history
- test_notifications_change_set
printing_ui:
- test_print_preview
- test_print_to_pdf
profile:
- test_set_default_profile
reader_view:
- test_improved_type_control_panel
- test_reader_view_close_sidebar
- test_reader_view_location_bar
scrolling_panning_zooming:
- test_default_zoom_persists
- test_mouse_wheel_zoom
- test_zoom_from_menu_bar
- test_zoom_menu_correlation
- test_zoom_text_only
security_and_privacy:
- test_blocking_cryptominers
- test_blocking_fingerprinters
- test_blocking_social_media_trackers
- test_cookies_not_saved_private_browsing
- test_cross_site_tracking_cookies_blocked
- test_cryptominers_blocked_and_shown_in_info_panel
- test_detected_blocked_trackers_found
- test_downloads_from_private_not_leaked
- test_https_enabled_private_browsing
- test_never_remember_browsing_history
- test_no_trackers_detected
- test_open_link_in_private_window
- test_phishing_and_malware_warnings
- test_private_browser_password_doorhanger
- test_private_session_awesome_bar_exclusion
- test_private_session_history_exclusion
- test_private_window_from_panelui
- test_third_party_content_blocked_private_browsing
- test_tls_v1_2_protocol
- test_trackers_crypto_fingerprint_blocked
- test_tracking_content_custom_mode
- test_undo_close_tab_private_browsing
tabs:
- test_active_tab
- test_list_all_tabs
- test_mute_tabs
- test_navigation_multiple_tabs
- test_open_bookmark_in_new_tab
- test_open_new_tab
- test_open_new_tab_keys
- test_open_new_tab_via_hyperlink
- test_pin_tab
- test_reopen_tab_through_context_menu
- test_reopen_tab_through_history_menu
- test_reopen_tabs_through_keys
theme_and_toolbar:
- test_customize_themes_and_redirect
- test_installed_theme_enabled
