name: Check new beta version - Functional

on:
  schedule:
    - cron: "30 * * * *"
env:
  LATEST: ""
permissions:
  contents: "write"

jobs:
  Get-Functional-Split:
    runs-on: ubuntu-latest
    outputs:
        split: ${{ steps.getsplit.outputs.split }}
    steps:
      - name: Get Split Based On Time
        id: getsplit
        run: echo "split=functional$(date +%H)" >> "$GITHUB_OUTPUT"

  Check-Beta-Version:
    needs: Get-Functional-Split
    runs-on: ubuntu-latest
    outputs:
      win_reportable: ${{ steps.reportable.outputs.win }}
      mac_reportable: ${{ steps.reportable.outputs.mac }}
      mac_l10n_reportable: ${{ steps.l10n-reportable.outputs.mac_l10n }}
      win_l10n_reportable: ${{ steps.l10n-reportable.outputs.win_l10n }}
      linux_l10n_reportable: ${{ steps.l10n-reportable.outputs.linux_l10n }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Check if the run is reportable
        id: reportable
        env:
          STARFOX_SPLIT: ${{ needs.Get-Functional-Split.outputs.split }}
          TESTRAIL_REPORT: true
          TESTRAIL_BASE_URL: ${{ secrets.TESTRAIL_BASE_URL }}
          TESTRAIL_API_KEY: ${{ secrets.TESTRAIL_API_KEY }}
          TESTRAIL_USERNAME: ${{ secrets.TESTRAIL_USERNAME }}
        run: |
          pip3 install 'pipenv==2023.11.15';
          pipenv install
          echo win=$(pipenv run python -c 'from modules import testrail_integration as tri; print(tri.reportable("Windows"))') >> "$GITHUB_OUTPUT"
          echo mac=$(pipenv run python -c 'from modules import testrail_integration as tri; print(tri.reportable("Darwin"))') >> "$GITHUB_OUTPUT"

  Run-Win-Functional:
    needs:
      - Check-Beta-Version
      - Get-Functional-Split
    if: ${{ needs.Check-Beta-Version.outputs.win_reportable == 'True' }}
    uses: ./.github/workflows/main.yml
    with:
      job_to_run: Test-Windows
      test_set: ${{ needs.Get-Functional-Split.outputs.split }}
    secrets: inherit

  Run-Mac-Functional:
    needs: Check-Beta-Version
    if: ${{ needs.Check-Beta-Version.outputs.mac_reportable == 'True' }}
    uses: ./.github/workflows/main.yml
    with:
      job_to_run: Test-MacOS
      test_set: ${{ needs.Get-Functional-Split.outputs.split }}
    secrets: inherit
