---
name: L10N output mapping splits

run-name: ${{ github.actor }} is writing L10N mapping splits
on:
  schedule:
    - cron: "0 0 * * 1"

permissions:
  contents: "write"

jobs:
  Select-Sites-Regions:
    runs-on: ubuntu-latest
    outputs:
      sites_regions: ${{ steps.splits.outputs.sites_regions }}
    steps:
      - name: Create app token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.BOT_CLIENT_ID }}
          private-key: ${{ secrets.BOT_PRIVATE_KEY }}
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
      - name: Select Sites and Regions
        id: splits
        run: |
          python3 scripts/choose_l10n_beta_split.py
